# Generated by Django 4.2.2 on 2023-06-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_phone_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
    ]
