# Generated by Django 4.2.2 on 2023-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clone_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
