# Generated by Django 4.2.2 on 2023-06-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_repe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repe_name',
            new_name='repo_name',
        ),
    ]
