# Generated by Django 4.2.2 on 2023-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='integrate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
