# Generated by Django 4.2.2 on 2023-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_integrate_workspace_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
