# Generated by Django 4.2.2 on 2023-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_actual_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
