# Generated by Django 4.2.2 on 2023-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_actual_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('s', 'TO Do'), ('p', 'In Progress'), ('t', 'Testing'), ('f', 'Failed'), ('d', 'Done'), ('c', 'Canceled')], default='t', max_length=1),
        ),
    ]
